---
  - include_vars: "vars/main.yml"

  - name: PHP | Install php7.0
    apt: pkg={{ item }} state=latest force=yes
    with_items:
      - php-fpm
      - php-mysql
      - php-cli
      - php-curl
      - php-gd
      - php-mbstring
      - php7.0-dom
      - php7.0-zip

  - name: PHP | Ensure listen.group is set.
    lineinfile: dest=/etc/php/7.0/fpm/pool.d/www.conf regexp='listen.group = www-data' line='listen.group = www-data' state=present
    notify: php7.0-fpm-restart

  - name: PHP | Ensure listen.owner is set.
    lineinfile: dest=/etc/php/7.0/fpm/pool.d/www.conf regexp='listen.owner = www-data' line='listen.owner = www-data' state=present
    notify: php7.0-fpm-restart

  - name: PHP | Ensure listen.mode is set.
    lineinfile: dest=/etc/php/7.0/fpm/pool.d/www.conf regexp='listen.mode = 0660' line='listen.mode = 0660' state=present
    notify: php7.0-fpm-restart

  - name: PHP | Add vendor/bin to the user's path
    shell: echo 'export PATH="$PATH:/var/www/vendor/bin"' >> ~/.bashrc

  - include_tasks:  roles/php7/tasks/composer_task.yml
